FROM ubuntu:14.04

RUN apt-get update && apt-get install -y python python-pip wget && pip install flask

ADD app.py /home/pyth/app.py
ADD log /home/pyth/log

RUN useradd -c 'Python user' -m -d /home/pyth -s /bin/bash pyth
RUN chown -R pyth.pyth /home
USER pyth
ENV HOME /home/pyth

WORKDIR /home/pyth

EXPOSE  5000
CMD ["python", "app.py"]

